backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Jewelry Products"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Main Image", name: "image", widget: "image" }
      - { label: "Offer Price (₹)", name: "price", widget: "number", value_type: "int" }
      - { label: "Original Price (₹)", name: "old_price", widget: "number", value_type: "int" }
      - { label: "Category", name: "category", widget: "select", options: ["Necklaces", "Earrings", "Bangles", "Rings"] }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Trending Product?", name: "trending", widget: "boolean", default: false }
